In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os 

In [2]:
os.chdir('C:\\Users\\Hp\\Desktop\\Pyt_language\\machine-learning\\Social_network_adds')

In [3]:
df = pd.read_csv('Social_Network_Ads_updated.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  11021175       1   42           121315          0
1  17782313       1   53            67214          0
2  14603818       0   59           111005          0
3  18188198       0   39            53414          0
4  19357305       1   39           114285          0

In [4]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175       1   42           121315          0
1    17782313       1   53            67214          0
2    14603818       0   59           111005          0
3    18188198       0   39            53414          0
4    19357305       1   39           114285          0
5    19524602       1   39           107458          0
6    19455396       0   20            85582          0
7    16879913       0   59           148335          1
8    11838352       1   48            80579          0
9    13118940       0   42           114204          0
10   19524480       0   32            87786          0
11   12784093       0   49           113544          0
12   12895966       1   55            88300          0
13   14674114       1   54           147066          0
14   12393248       1   57           139622          0
15   18842131       1   41           134716          0
16   11060500       1   51           116333          1
17   14887406       1   55            72567          1
18   12606442       1   44           123254          1
19   17919323       0   47           113548          1
20   17207101       1   52            79343          1
21   17159912       0   20           106149          1
22   10718832       1   40            59674          1
23   16952550       0   52            76333          1
24   10494682       1   28           118742          1
25   16824758       1   22           105897          1
26   11168323       1   25           114815          1
27   16945283       0   38            85428          1
28   13865670       1   57           114005          0
29   16924204       1   57           133402          0
30   10877441       1   43           106726          0
31   16751398       0   35            84550          1
32   10393028       0   34            96296          0
33   18915643       0   32            68964          0
34   12430332       1   55            90946          0
35   16222500       1   48            51787          0
36   10179619       0   22            53940          0
37   19088014       1   42           138928          0
38   15101607       0   59           116474          0
39   11468592       0   23            97284          0
40   19207686       0   40           132951          0
41   16970151       0   24           119308          0
42   12111836       1   50           120675          0
43   19889978       1   41           113547          0
44   19252002       0   52           102686          0
45   15836350       1   34           140262          0
46   15448575       1   20            54075          0
47   16700977       0   25            63715          0
48   15363592       1   46            56058          1
49   19732707       0   58            65052          0
50   13316736       0   38            72107          0
51   12312881       0   21           108656          0
52   14328688       0   42           120639          0
53   11182761       0   31            68033          0
54   14748686       0   26            80283          0
55   12639188       0   47            60952          0
56   12748022       0   31           123137          0
57   16319219       1   36            98529          0
58   12475031       1   25           121301          0
59   15626349       0   28            61144          0
60   16736728       1   41           107405          0
61   10975744       1   32            87032          0
62   11737743       0   53           118544          0
63   10022583       1   38            63743          1
64   12170069       0   43            53404          0
65   15582531       1   34            88672          0
66   16854184       1   29            96164          0
67   19722370       0   47           123288          0
68   13180998       0   31           122623          0
69   15095883       0   31            78696          0
70   11791767       1   51           142525          0
71   10834754       0   59            87656   

In [5]:
x = df.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],


In [6]:
y = df.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [7]:
x.shape

(400, 2)

In [8]:
y.shape

(400,)

In [9]:
from sklearn.preprocessing import StandardScaler
SC_x = StandardScaler()
x = SC_x.fit_transform(x)
x

array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
x_train

array([[ 0.00976078,  0.29541661],
       [ 1.622412  ,  0.39722026],
       [-1.60289043,  0.83672264],
       [-1.09363215, -1.00089486],
       [-0.41462111, -0.35697359],
       [ 0.60389544,  0.21136245],
       [-1.26338491,  1.56420405],
       [-0.32974473, -0.04302315],
       [ 0.60389544,  0.65294677],
       [-0.58437387, -0.46336457],
       [-1.68776681, -1.61168143],
       [ 0.26438992,  0.24622622],
       [-0.49949749, -0.12181953],
       [ 1.02827734,  0.89773425],
       [ 1.28290648, -1.54587075],
       [ 0.00976078,  0.25938836],
       [ 1.1980301 ,  1.66971285],
       [-0.83900301,  1.10017705],
       [ 1.02827734, -0.8786952 ],
       [-1.60289043, -0.83649168],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.95567587],
       [-0.0751156 , -0.29162165],
       [-0.66925025, -0.70352942],
       [-0.0751156 ,  0.02306982],
       [ 0.43414268, -0.06715962],
       [-1.34826129, -1.40507473],
       [-0.0751156 , -0.57684828],
       [-1.26338491,

In [11]:
x_train.shape

(320, 2)

In [12]:
x_test.shape

(80, 2)

In [13]:
y_train.shape

(320,)

In [14]:
y_test.shape

(80,)

In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [16]:
classifier.score(x_test,y_test)

0.6625

In [17]:
y_pred = classifier.predict(x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

0.9325

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       257
           1       0.95      0.86      0.90       143

    accuracy                           0.93       400
   macro avg       0.94      0.92      0.92       400
weighted avg       0.93      0.93      0.93       400



In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y,y_pred)
print(cm)

[[250   7]
 [ 20 123]]


In [21]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='gini')
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
y_pred = classifier.predict(x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

0.935

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95       257
           1       0.91      0.90      0.91       143

    accuracy                           0.94       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.93      0.94      0.93       400



In [25]:
from sklearn.metrics import confusion_matrix 
print(confusion_matrix(y,y_pred))

[[245  12]
 [ 14 129]]
