In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [21]:
#os.chdir('C:\\Users\Hp\Desktop\\Pyt_language\\machine-learning')
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    11021175    Male   42           121315          0
1    17782313    Male   53            67214          0
2    14603818  Female   59           111005          0
3    18188198  Female   39            53414          0
4    19357305    Male   39           114285          0
..        ...     ...  ...              ...        ...
395  10220446  Female   20           141231          1
396  12387292    Male   50            75848          1
397  10715173  Female   25            82560          1
398  10016842    Male   55           147667          0
399  11699655  Female   54           134972          1

[400 rows x 5 columns]

In [22]:
x = df.iloc[:,2:4]
x

Age  EstimatedSalary
0     42           121315
1     53            67214
2     59           111005
3     39            53414
4     39           114285
..   ...              ...
395   20           141231
396   50            75848
397   25            82560
398   55           147667
399   54           134972

[400 rows x 2 columns]

In [23]:
x = df.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],


In [24]:
y = df.iloc[:,4]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [25]:
y.shape

(400,)

In [26]:
y = df.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [27]:
# Feature Scaling – Standardization (To standardize Salary)

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
x

In [28]:
x.size

800

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
x_train

array([[    43,  91205],
       [    23,  59666],
       [    44,  95919],
       [    28,  74078],
       [    25,  89304],
       [    52, 102686],
       [    24, 138809],
       [    28,  96148],
       [    21, 123460],
       [    40,  59674],
       [    36,  52183],
       [    35,  69596],
       [    25, 149284],
       [    22, 111361],
       [    26,  68131],
       [    58,  78749],
       [    40,  75308],
       [    31, 127446],
       [    39, 107871],
       [    59,  80400],
       [    21,  76043],
       [    39, 138840],
       [    44, 145967],
       [    55, 147667],
       [    31, 103674],
       [    57, 101429],
       [    55,  90946],
       [    57, 106814],
       [    28, 119752],
       [    22,  87705],
       [    51, 142525],
       [    41, 107405],
       [    47, 113548],
       [    44, 113742],
       [    44, 123254],
       [    46,  87539],
       [    59, 111005],
       [    20,  64957],
       [    43, 149365],
       [    41, 107820],


In [30]:
from sklearn.preprocessing import StandardScaler
x_trainsc = StandardScaler()
x_train = x_trainsc.fit_transform(x_train)


In [31]:
x_test = x_trainsc.transform(x_test)
x_test

array([[-0.73481221,  0.82450024],
       [ 1.10417746,  0.58502547],
       [-1.31994528,  1.54093387],
       [-1.40353572,  1.45791921],
       [-0.40045045, -0.4844562 ],
       [-0.31686001, -0.87969259],
       [-1.48712616,  1.66683536],
       [ 0.35186351,  0.86417405],
       [ 1.60572009, -0.85954137],
       [-0.98558352, -0.14607629],
       [ 0.60263482, -0.25978926],
       [-0.90199308, -0.51899616],
       [ 0.26827307,  0.79380193],
       [-0.14967913, -0.45379281],
       [-1.31994528,  0.67673624],
       [-1.31994528,  0.72943676],
       [ 1.1877679 ,  1.27648835],
       [-0.73481221, -1.12325348],
       [-0.65122177,  1.78571711],
       [-0.73481221,  1.25043495],
       [-0.06608869,  0.55401284],
       [ 0.43545394, -0.09767144],
       [ 0.18468263,  0.77592077],
       [ 0.68622526,  0.75838886],
       [ 0.85340614,  1.77813857],
       [-1.40353572,  1.4835186 ],
       [-0.98558352,  0.44532895],
       [-0.23326957,  1.3690373 ],
       [ 1.68931053,

In [32]:
x_train.size

640

In [33]:
x_test.size

160

In [34]:
y_train.shape

(320,)

In [35]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [36]:
y_pred = logmodel.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [37]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [38]:
from sklearn.metrics import classification_report
print(classification_report (y_test,y_pred))

              precision    recall  f1-score   support

           0       0.66      1.00      0.80        53
           1       0.00      0.00      0.00        27

    accuracy                           0.66        80
   macro avg       0.33      0.50      0.40        80
weighted avg       0.44      0.66      0.53        80



C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Abhinav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[53  0]
 [27  0]]


In [40]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test,y_pred)

0.6625