In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import os
from sklearn.metrics import r2_score

In [3]:
os.getcwd()

'C:\\Users\\Abhinav\\Downloads\\ML\\machine-learning'

In [4]:
#os.chdir('C:\\Users\\Hp\\Desktop\\Pyt_language\\machine-learning')
df = pd.read_csv('50_Startups.csv')
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
x = df.iloc[:,:-1]
x

R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42  California
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68    New York
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95  California
11  100671.96        91790.61        249744.55     Florida
12   93863.75       127320.38        249839.44  California
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57    New York
19   86419.70       153514.11             0.00     Florida
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26  California
23   67532.53       105751.03        304768.73  California
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07    New York
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24    New York
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81    New York
34   46426.07       157693.92        210797.67     Florida
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82    New York
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67     Florida
41   27892.92        84710.77        164470.71  California
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [6]:
x = df.iloc[:,:-1].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'California'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'New York'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'California'],
       [100671.96, 91790.61, 249744.55, 'Florida'],
       [93863.75, 127320.38, 249839.44, 'California'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79

In [7]:
y = df.iloc[:,4]
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [8]:
y = df.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [9]:
from sklearn.preprocessing import LabelEncoder
Label = LabelEncoder()
x[:,3] = Label.fit_transform(x[:,3])
print (x)


[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 0]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 2]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 0]
 [100671.96 91790.61 249744.55 1]
 [93863.75 127320.38 249839.44 0]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 2]
 [86419.7 153514.11 0.0 1]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 0]
 [67532.53 105751.03 304768.73 0]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 2]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn. preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('en',OneHotEncoder(), [3] )],remainder='passthrough')
x1 = ct.fit_transform(x)
x1
# when i want to update x varible

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 0.0, 1.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 1.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [11]:
    print (pd.DataFrame(x1))

      0    1    2          3          4          5
0   0.0  0.0  1.0   165349.2   136897.8   471784.1
1   1.0  0.0  0.0   162597.7  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0   131876.9   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  0.0  1.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  0.0  101913.08  110594.11  229160.95
11  0.0  1.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  0.0  1.0   91749.16  1

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 1/5)
x_train

array([[20229.59, 65947.93, 185265.1, 2],
       [61136.38, 152701.92, 88218.23, 2],
       [27892.92, 84710.77, 164470.71, 0],
       [28663.76, 127056.21, 201126.82, 2],
       [91992.39, 135495.07, 252664.93, 0],
       [101913.08, 110594.11, 229160.95, 0],
       [77044.01, 99281.34, 140574.81, 2],
       [142107.34, 91391.77, 366168.42, 0],
       [165349.2, 136897.8, 471784.1, 2],
       [73994.56, 122782.75, 303319.26, 0],
       [15505.73, 127382.3, 35534.17, 2],
       [63408.86, 129219.61, 46085.25, 0],
       [120542.52, 148718.95, 311613.29, 2],
       [64664.71, 139553.16, 137962.62, 0],
       [67532.53, 105751.03, 304768.73, 0],
       [61994.48, 115641.28, 91131.24, 2],
       [22177.74, 154806.14, 28334.72, 0],
       [28754.33, 118546.05, 172795.67, 1],
       [1000.23, 124153.04, 1903.93, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [134615.46, 147198.87, 127716.82, 0],
       [542.05, 51743.15, 0.0, 2],
       [91749.16, 114175.79, 294919.57, 2],
       [9

In [13]:
x_train.shape

(40, 4)

In [14]:
y_train.shape

(40,)

In [15]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [16]:
y_pred = reg.predict(x_test)
y_pred

array([ 83327.63772655, 103758.02349294, 148935.06957058, 166412.71558175,
       116715.37448858,  55228.23622021,  89326.41001133, 151551.54088769,
       112726.2006428 ,  89406.75596726])

In [17]:
y_test

array([ 81005.76, 101004.64, 129917.04, 156991.12, 118474.03,  49490.75,
        89949.14, 132602.65, 105733.54,  96712.8 ])

In [18]:
x_test

array([[38558.51, 82982.09, 174999.3, 0],
       [65605.48, 153032.06, 107138.38, 2],
       [114523.61, 122616.84, 261776.23, 2],
       [131876.9, 99814.71, 362861.36, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [1315.46, 115816.21, 297114.46, 1],
       [44069.95, 51283.14, 197029.42, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [75328.87, 144135.98, 134050.07, 2],
       [46426.07, 157693.92, 210797.67, 1]], dtype=object)

In [19]:
r2_score(y_pred,y_test)

0.9130090527924242

In [20]:
y_pred = reg.predict(x)
y_pred

array([195766.03185041, 190808.83184096, 184559.37796591, 176740.00624587,
       173626.32119647, 166412.71558175, 160095.64921983, 162874.10345574,
       154392.75784015, 156086.64465167, 136429.99139126, 137223.00771022,
       129775.32217952, 128059.53877703, 151551.54088769, 148935.06957058,
       117131.38212178, 132314.32853933, 131070.20378499, 117643.12112473,
       116715.37448858, 118981.24600848, 114700.74980055, 109853.45321319,
       115572.5893873 , 102505.43671345, 112726.2006428 , 115785.25317718,
       102760.31809493, 103758.02349294, 101431.35695861,  99603.11975739,
        99543.94646833,  99363.63963404,  89406.75596726,  91785.10960388,
        76094.71055711,  89326.41001133,  70438.16618509,  83327.63772655,
        74931.31025268,  74174.05264716,  69925.00260188,  61180.8115731 ,
        64176.69205477,  48424.48390964,  55228.23622021,  45636.37042519,
        50042.11395745,  47243.93712275])

In [21]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [22]:
r2_score (y_pred , y)

0.9487034671376741

In [23]:
reg.coef_

array([ 8.29906127e-01, -2.82239341e-02,  2.40636630e-02,  7.97003851e+02])

In [24]:
x1

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 0.0, 1.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 1.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [25]:
reg.intercept_

49458.65089693282

In [26]:
result = pd.concat([pd.DataFrame(y_pred),pd.DataFrame(y)],axis =1)
print(result)

                0          0
0   195766.031850  192261.83
1   190808.831841  191792.06
2   184559.377966  191050.39
3   176740.006246  182901.99
4   173626.321196  166187.94
5   166412.715582  156991.12
6   160095.649220  156122.51
7   162874.103456  155752.60
8   154392.757840  152211.77
9   156086.644652  149759.96
10  136429.991391  146121.95
11  137223.007710  144259.40
12  129775.322180  141585.52
13  128059.538777  134307.35
14  151551.540888  132602.65
15  148935.069571  129917.04
16  117131.382122  126992.93
17  132314.328539  125370.37
18  131070.203785  124266.90
19  117643.121125  122776.86
20  116715.374489  118474.03
21  118981.246008  111313.02
22  114700.749801  110352.25
23  109853.453213  108733.99
24  115572.589387  108552.04
25  102505.436713  107404.34
26  112726.200643  105733.54
27  115785.253177  105008.31
28  102760.318095  103282.38
29  103758.023493  101004.64
30  101431.356959   99937.59
31   99603.119757   97483.56
32   99543.946468   97427.84
33   99363.639

In [27]:
y_pre =pd.DataFrame(y_pred, columns=['Prediction'])
y_te =pd.DataFrame(y,columns=['Actual'])
x_te =pd.DataFrame(x1,columns=['CF','FR','New y','R&D','Admin','Mark'])
result = pd.concat([x_te,y_te,y_pre],axis = 1)
print (result)

     CF   FR New y        R&D      Admin       Mark     Actual     Prediction
0   0.0  0.0   1.0   165349.2   136897.8   471784.1  192261.83  195766.031850
1   1.0  0.0   0.0   162597.7  151377.59  443898.53  191792.06  190808.831841
2   0.0  1.0   0.0  153441.51  101145.55  407934.54  191050.39  184559.377966
3   0.0  0.0   1.0  144372.41  118671.85  383199.62  182901.99  176740.006246
4   1.0  0.0   0.0  142107.34   91391.77  366168.42  166187.94  173626.321196
5   0.0  0.0   1.0   131876.9   99814.71  362861.36  156991.12  166412.715582
6   1.0  0.0   0.0  134615.46  147198.87  127716.82  156122.51  160095.649220
7   0.0  0.0   1.0  130298.13  145530.06  323876.68  155752.60  162874.103456
8   0.0  0.0   1.0  120542.52  148718.95  311613.29  152211.77  154392.757840
9   1.0  0.0   0.0  123334.88  108679.17  304981.62  149759.96  156086.644652
10  1.0  0.0   0.0  101913.08  110594.11  229160.95  146121.95  136429.991391
11  0.0  1.0   0.0  100671.96   91790.61  249744.55  144259.40  

In [28]:
#anather way to find accuricy without any predicted value
x1=x1.astype('float64')
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x1)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     171.2
Date:                Tue, 19 Jul 2022   Prob (F-statistic):           1.14e-27
Time:                        09:34:37   Log-Likelihood:                -525.19
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          5.062e+04   6806.869      7.436      0.0

In [29]:
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [30]:
x_new = df.iloc[:,:-2].values
x_new

array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34,  91391.77, 366168.42],
       [131876.9 ,  99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [ 78013.11, 121597.55, 264346.06],
       [ 94657.16, 145077.58, 282574.31],
       [ 91749.16, 114175.79, 294919.57],
       [ 86419.7 , 153514.11,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78389.47, 153773.43, 299737.29],
       [ 73994.56, 122782.75, 303319.26],
       [ 67532.53, 105751.03, 3047

In [31]:
x_new=x_new.astype('float64')
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x_new)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              1232.
Date:                Tue, 19 Jul 2022   Prob (F-statistic):                    1.17e-44
Time:                        09:34:38   Log-Likelihood:                         -545.82
No. Observations:                  50   AIC:                                      1098.
Df Residuals:                      47   BIC:                                      1103.
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------