In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import os 

In [2]:
os.chdir('C:\\Users\\Hp\\Desktop\\Pyt_language\\machine-learning\\Social_network_adds')
df = pd.read_csv('Social_Network_Ads_updated.csv')
df.head(50)

User ID  Gender  Age  EstimatedSalary  Purchased
0   11021175       1   42           121315          0
1   17782313       1   53            67214          0
2   14603818       0   59           111005          0
3   18188198       0   39            53414          0
4   19357305       1   39           114285          0
5   19524602       1   39           107458          0
6   19455396       0   20            85582          0
7   16879913       0   59           148335          1
8   11838352       1   48            80579          0
9   13118940       0   42           114204          0
10  19524480       0   32            87786          0
11  12784093       0   49           113544          0
12  12895966       1   55            88300          0
13  14674114       1   54           147066          0
14  12393248       1   57           139622          0
15  18842131       1   41           134716          0
16  11060500       1   51           116333          1
17  14887406       1   55            72567          1
18  12606442       1   44           123254          1
19  17919323       0   47           113548          1
20  17207101       1   52            79343          1
21  17159912       0   20           106149          1
22  10718832       1   40            59674          1
23  16952550       0   52            76333          1
24  10494682       1   28           118742          1
25  16824758       1   22           105897          1
26  11168323       1   25           114815          1
27  16945283       0   38            85428          1
28  13865670       1   57           114005          0
29  16924204       1   57           133402          0
30  10877441       1   43           106726          0
31  16751398       0   35            84550          1
32  10393028       0   34            96296          0
33  18915643       0   32            68964          0
34  12430332       1   55            90946          0
35  16222500       1   48            51787          0
36  10179619       0   22            53940          0
37  19088014       1   42           138928          0
38  15101607       0   59           116474          0
39  11468592       0   23            97284          0
40  19207686       0   40           132951          0
41  16970151       0   24           119308          0
42  12111836       1   50           120675          0
43  19889978       1   41           113547          0
44  19252002       0   52           102686          0
45  15836350       1   34           140262          0
46  15448575       1   20            54075          0
47  16700977       0   25            63715          0
48  15363592       1   46            56058          1
49  19732707       0   58            65052          0

In [3]:
x = df.iloc[:,2:4].values
x

array([[    42, 121315],
       [    53,  67214],
       [    59, 111005],
       [    39,  53414],
       [    39, 114285],
       [    39, 107458],
       [    20,  85582],
       [    59, 148335],
       [    48,  80579],
       [    42, 114204],
       [    32,  87786],
       [    49, 113544],
       [    55,  88300],
       [    54, 147066],
       [    57, 139622],
       [    41, 134716],
       [    51, 116333],
       [    55,  72567],
       [    44, 123254],
       [    47, 113548],
       [    52,  79343],
       [    20, 106149],
       [    40,  59674],
       [    52,  76333],
       [    28, 118742],
       [    22, 105897],
       [    25, 114815],
       [    38,  85428],
       [    57, 114005],
       [    57, 133402],
       [    43, 106726],
       [    35,  84550],
       [    34,  96296],
       [    32,  68964],
       [    55,  90946],
       [    48,  51787],
       [    22,  53940],
       [    42, 138928],
       [    59, 116474],
       [    23,  97284],


In [4]:
y = df.iloc[:,4]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [5]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
x

array([[ 0.17951354,  0.76103154],
       [ 1.11315372, -1.14804259],
       [ 1.622412  ,  0.39722026],
       [-0.0751156 , -1.63500628],
       [-0.0751156 ,  0.51296235],
       [-0.0751156 ,  0.27205647],
       [-1.68776681, -0.49988685],
       [ 1.622412  ,  1.71449234],
       [ 0.68877182, -0.67642883],
       [ 0.17951354,  0.51010409],
       [-0.66925025, -0.42211381],
       [ 0.7736482 ,  0.48681452],
       [ 1.28290648, -0.40397617],
       [ 1.1980301 ,  1.66971285],
       [ 1.45265924,  1.40703476],
       [ 0.09463716,  1.23391563],
       [ 0.94340096,  0.58523059],
       [ 1.28290648, -0.95915007],
       [ 0.3492663 ,  0.82945347],
       [ 0.60389544,  0.48695567],
       [ 1.02827734, -0.72004384],
       [-1.68776681,  0.2258655 ],
       [ 0.00976078, -1.41410826],
       [ 1.02827734, -0.82625839],
       [-1.00875577,  0.67023751],
       [-1.51801405,  0.21697311],
       [-1.26338491,  0.53166458],
       [-0.15999198, -0.50532108],
       [ 1.45265924,

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
x_train

array([[-1.17850853,  0.51370338],
       [ 0.17951354, -0.96465488],
       [ 1.36778286, -1.46213417],
       [ 0.7736482 ,  0.85179028],
       [-0.92387939, -0.57120233],
       [ 0.17951354,  1.38254542],
       [ 0.60389544, -1.36901118],
       [-0.66925025,  1.75747218],
       [-0.75412663,  0.78626191],
       [-0.41462111,  0.59525216],
       [-0.24486835,  1.59769163],
       [-0.66925025,  1.1500379 ],
       [ 1.1980301 , -1.63175986],
       [ 0.26438992, -0.75448417],
       [ 1.28290648, -0.95915007],
       [ 0.00976078,  1.43385305],
       [ 1.02827734, -0.58570538],
       [ 1.45265924,  1.40703476],
       [ 1.1980301 , -0.74294525],
       [ 1.1980301 , -0.36223139],
       [ 1.53753562, -0.74100445],
       [-0.32974473,  1.23977331],
       [ 1.11315372, -0.28505823],
       [-0.75412663, -0.74287468],
       [ 0.68877182, -1.6924186 ],
       [ 0.09463716,  0.27018625],
       [-1.26338491, -1.27151258],
       [ 0.7736482 ,  1.02042793],
       [ 0.94340096,

In [7]:
from sklearn.svm import SVC
classifier = SVC(kernel='sigmoid')
classifier.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [8]:
y_pred = classifier.predict(x)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,

In [17]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [22]:
df_x = pd.DataFrame(x,columns = ['Age','EstimatedSalary'])
df_y = pd.DataFrame(y,columns = ['Y'])
df_ypred = pd.DataFrame(y_pred,columns = ['Y_pred'])
result = pd.concat([df_x,df_y,df_ypred],axis = 1)
print(result.head(100))

         Age  EstimatedSalary    Y  Y_pred
0   0.179514         0.761032  NaN       0
1   1.113154        -1.148043  NaN       0
2   1.622412         0.397220  NaN       0
3  -0.075116        -1.635006  NaN       0
4  -0.075116         0.512962  NaN       0
..       ...              ...  ...     ...
95  0.943401        -0.143909  NaN       0
96 -0.499497         1.527823  NaN       0
97  1.622412         1.344435  NaN       0
98 -0.329745        -1.678445  NaN       0
99 -0.329745        -0.709775  NaN       0

[100 rows x 4 columns]


In [10]:
from sklearn.metrics import accuracy_score 
accuracy_score(y,y_pred)

0.5775

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y,y_pred)
print(cm)

[[177  80]
 [ 89  54]]


In [12]:
from sklearn.metrics import classification_report 
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.69      0.68       257
           1       0.40      0.38      0.39       143

    accuracy                           0.58       400
   macro avg       0.53      0.53      0.53       400
weighted avg       0.57      0.58      0.57       400



In [13]:
df_x = pd.DataFrame(df)
df_y = pd.DataFrame(y,columns = ['Y'])
df_ypred = pd.DataFrame(y_pred, columns = ['ypred'])
result = pd.concat([df_x,df_y,df_ypred],axis = 1)
print(result.head(50))
result.to_excel('C:\\Users\\Hp\\Desktop\\Pyt_language\\machine-learning\\Social_network_adds.xlsx')

     User ID  Gender  Age  EstimatedSalary  Purchased    Y  ypred
0   11021175       1   42           121315          0  NaN      0
1   17782313       1   53            67214          0  NaN      0
2   14603818       0   59           111005          0  NaN      1
3   18188198       0   39            53414          0  NaN      0
4   19357305       1   39           114285          0  NaN      0
5   19524602       1   39           107458          0  NaN      0
6   19455396       0   20            85582          0  NaN      0
7   16879913       0   59           148335          1  NaN      0
8   11838352       1   48            80579          0  NaN      0
9   13118940       0   42           114204          0  NaN      0
10  19524480       0   32            87786          0  NaN      0
11  12784093       0   49           113544          0  NaN      0
12  12895966       1   55            88300          0  NaN      1
13  14674114       1   54           147066          0  NaN      0
14  123932

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf')
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x)
print(accuracy_score(y,y_pred))
print(classification_report(y,y_pred))
print(confusion_matrix(y,y_pred))

0.6425
              precision    recall  f1-score   support

           0       0.64      1.00      0.78       257
           1       0.00      0.00      0.00       143

    accuracy                           0.64       400
   macro avg       0.32      0.50      0.39       400
weighted avg       0.41      0.64      0.50       400

[[257   0]
 [143   0]]


C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly')
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x)
print(accuracy_score (y,y_pred))
cm =confusion_matrix(y,y_pred)
print(cm)
print(classification_report(y,y_pred))

0.6425
[[257   0]
 [143   0]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78       257
           1       0.00      0.00      0.00       143

    accuracy                           0.64       400
   macro avg       0.32      0.50      0.39       400
weighted avg       0.41      0.64      0.50       400



C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear')
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x)
print(accuracy_score (y,y_pred))
print(classification_report(y,y_pred))
cm = confusion_matrix(y,y_pred)
print(cm)

0.6425
              precision    recall  f1-score   support

           0       0.64      1.00      0.78       257
           1       0.00      0.00      0.00       143

    accuracy                           0.64       400
   macro avg       0.32      0.50      0.39       400
weighted avg       0.41      0.64      0.50       400

[[257   0]
 [143   0]]


C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
